### ISSUE TITLE
Block setup wizard

### ISSUE THREAD

**Issue by jeffpaul** [10up/maps-block-apple#66]
**Is your enhancement related to a problem? Please describe.**
In discussing how best to handle an in-Gutenberg block-specific settings config today with @fabiankaegy he mentioned we could try to utilize the Gutenberg helper components (like what you see when you first load Gutenberg) to do a multi-step set up process to walk a user through each step in creating the MapKit JS credentials needed for the Apple Maps block to function properly (aka "block setup wizard" 🧱🏗️🧙).

**Describe the solution you'd like**

- [ ] investigate what Gutenberg helper components are available to use/apply to our desired use case
- [ ] prototype multi-step process
- [ ] if prototype shows positive results, then design eventual block setup wizard
- [ ] implement designs of block setup wizard

**Designs**

TBD assuming prototype shows positive results.

**Describe alternatives you've considered**

Don't implement a block setup wizard and keep with the in-block initial state setup config copy/fields.

**Additional context**

Assuming this is feasible and works out well, this would make for a nice external blog post to share how this was created for other block developers to utilize.

**Comment by Sidsector9** [comment]
@jeffpaul I picked this up and here's my suggestion:

1. The Welcome Guide that Gutenberg shows on fresh installs is shown in a popup and blocks the entire editor with an overlay until its dismissed. It makes sense to do that because the welcome guide is an intro to the editor. IMO, semantically, a Block shouldn't block the entire editor for an intro guide.
2. Secondly, if the Setup Wizard is shown in a guide and dismissed by the user before setting up, how should we display it again? It would be counter-intuitive for the user to click somewhere on the block to re-open the Setup Wizard.

My suggestion is to implement the multi-step setup wizard within the block itself. Here's the design an flow I came up with:


https://github.com/10up/maps-block-apple/assets/17757960/20466a49-a2a1-45fb-84ee-1ccb7d917901

Please let me know your thoughts on this. Thanks!

**Comment by jeffpaul** [comment]
@Sidsector9 yeah, that prototype seems good... though as long as the setup flow that exists within the plugin settings page works and users are provided with a path there when trying to use an un-authed access for the block, then that's probably fine as-is and don't likely need to go this further step with in-block setup?

**Comment by Sidsector9** [comment]
Yeah the current implementation does that. I'll close this issue as not needed.
